const demoProducts = [
  {id:'demo-1',variantId:'demo-v1',title:'Lip Peptide Treatment',subtitle:'Softening clear treatment',type:'Treatment',price:18,badge:'Bestseller',number:'01',image:'assets/halo-pink-botanical.jpg'},
  {id:'demo-2',variantId:'demo-v2',title:'Peptide Lip Tint',subtitle:'Pink veil',type:'Tint',price:18,badge:'New',number:'02',image:'assets/halo-lifestyle.jpg'},
  {id:'demo-3',variantId:'demo-v3',title:'Peptide Lip Tint',subtitle:'Cocoa rose',type:'Tint',price:18,badge:'',number:'03',image:'assets/halo-trio-blue.jpg'},
  {id:'demo-4',variantId:'demo-v4',title:'The Halo Lip Trio',subtitle:'Three everyday shades',type:'Set',price:48,badge:'Save £6',number:'04',image:'assets/halo-trio-warm.jpg'}
];
let products=[], cart=JSON.parse(localStorage.getItem('halo_cart')||'[]'), appliedDiscount='', checkoutSubtotal=0, checkoutDiscount=0;
const money=n=>new Intl.NumberFormat('en-GB',{style:'currency',currency:'GBP'}).format(n);
function loadProducts(){products=demoProducts;renderProducts()}
function renderProducts(filter='all'){const list=products.filter(p=>filter==='all'||p.type===filter);document.querySelector('#product-grid').innerHTML=list.map(p=>`<article class="product-card"><div class="product-image">${p.badge?`<span class="badge">${p.badge}</span>`:''}${p.image?`<img src="${p.image}" alt="${p.title}">`:`<div class="product-bottle" data-number="${p.number}">HALO</div>`}<button class="quick-add" data-add="${p.variantId}" ${p.available===false?'disabled':''}>${p.available===false?'Sold out':'Quick add — '+money(p.price)}</button></div><div class="product-meta"><h3>${p.title}</h3><p>${p.subtitle}</p><span class="product-price">${money(p.price)}</span></div></article>`).join('');document.querySelectorAll('[data-add]').forEach(b=>b.onclick=()=>addToCart(b.dataset.add))}
function addToCart(variantId){const p=products.find(x=>x.variantId===variantId);if(!p)return;
  const item=cart.find(x=>x.variantId===variantId);item?item.quantity++:cart.push({...p,quantity:1});saveCart();toast(`${p.title} added to your bag`);openDrawer(document.querySelector('.cart-drawer'))}
function saveCart(){localStorage.setItem('halo_cart',JSON.stringify(cart));renderCart()}
function changeQty(id,delta){const item=cart.find(x=>x.variantId===id);if(!item)return;item.quantity+=delta;if(item.quantity<=0)cart=cart.filter(x=>x.variantId!==id);saveCart()}
function renderCart(){const total=cart.reduce((s,x)=>s+x.price*x.quantity,0),count=cart.reduce((s,x)=>s+x.quantity,0);document.querySelectorAll('.cart-count').forEach(e=>e.textContent=`(${count})`);document.querySelector('#cart-items').innerHTML=cart.map(x=>`<div class="cart-item"><div class="cart-thumb">${x.image?`<img src="${x.image}" alt="" style="width:100%;height:100%;object-fit:cover">`:`<div class="product-bottle" data-number="${x.number}">H</div>`}</div><div><h4>${x.title}</h4><p>${x.subtitle}</p><div class="quantity"><button data-qty="${x.variantId}" data-delta="-1">−</button><span>${x.quantity}</span><button data-qty="${x.variantId}" data-delta="1">+</button></div></div><div><b>${money(x.price*x.quantity)}</b><br><button class="remove" data-remove="${x.variantId}">Remove</button></div></div>`).join('');document.querySelector('#cart-subtotal').textContent=money(total);document.querySelector('#delivery-remaining').textContent=money(Math.max(0,45-total));document.querySelector('.cart-progress span').style.width=Math.min(100,total/45*100)+'%';document.querySelector('#cart-empty').style.display=cart.length?'none':'block';document.querySelector('#cart-footer').style.display=cart.length?'block':'none';document.querySelectorAll('[data-qty]').forEach(b=>b.onclick=()=>changeQty(b.dataset.qty,Number(b.dataset.delta)));document.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{const x=cart.find(i=>i.variantId===b.dataset.remove);if(x)changeQty(x.variantId,-x.quantity)})}
function openDrawer(el){document.querySelectorAll('.drawer,.search-panel').forEach(x=>x.classList.remove('open'));el.classList.add('open');el.setAttribute('aria-hidden','false');document.querySelector('[data-overlay]').classList.add('open');document.body.style.overflow='hidden'}
function closeAll(){document.querySelectorAll('.drawer,.search-panel').forEach(x=>{x.classList.remove('open');x.setAttribute('aria-hidden','true')});document.querySelector('[data-overlay]').classList.remove('open');document.body.style.overflow=''}
let toastTimer;function toast(msg){const t=document.querySelector('.toast');t.textContent=msg;t.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>t.classList.remove('show'),2600)}
document.querySelector('[data-cart-open]').onclick=()=>openDrawer(document.querySelector('.cart-drawer'));document.querySelector('[data-menu-open]').onclick=()=>openDrawer(document.querySelector('.menu-drawer'));document.querySelectorAll('[data-drawer-close],[data-overlay]').forEach(b=>b.onclick=closeAll);document.querySelector('[data-search-open]').onclick=()=>{openDrawer(document.querySelector('.search-panel'));setTimeout(()=>document.querySelector('#search-input').focus(),300)};document.querySelector('[data-search-close]').onclick=closeAll;
document.querySelectorAll('.filter').forEach(b=>b.onclick=()=>{document.querySelectorAll('.filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');renderProducts(b.dataset.filter)});
document.querySelector('#search-input').oninput=e=>{const term=e.target.value.toLowerCase();const hits=products.filter(p=>p.title.toLowerCase().includes(term)||p.subtitle.toLowerCase().includes(term));document.querySelector('#search-results').innerHTML=term?(hits.length?hits.map(p=>`<a href="#shop" onclick="closeAll()">${p.title} — ${money(p.price)}</a>`).join('<br>'):'No products found.'):''};
document.querySelector('#newsletter-form').onsubmit=e=>{e.preventDefault();e.target.querySelector('.form-message').textContent='Welcome to our orbit. Check your inbox soon.';e.target.reset()};
document.querySelector('#apply-discount').onclick=()=>{const code=document.querySelector('#discount-code').value.trim().toUpperCase();if(!code)return;if(code==='HALO10'){appliedDiscount=code;toast('HALO10 applied — 10% off')}else toast('That discount code is not recognised')};
function selectedDeliveryMethod(){return document.querySelector('input[name="deliveryMethod"]:checked')?.value||'standard'}
function renderCheckoutTotals(){const method=window.HaloDelivery.METHODS[selectedDeliveryMethod()],delivery=method.price,total=checkoutSubtotal-checkoutDiscount+delivery;document.querySelector('#checkout-subtotal').textContent=money(checkoutSubtotal-checkoutDiscount);document.querySelector('#checkout-delivery').textContent=money(delivery);document.querySelector('#checkout-total').textContent=money(total)}
function checkoutAddress(){const form=document.querySelector('#checkout-form');return{address:form.elements.address.value.trim(),city:form.elements.city.value.trim(),postcode:form.elements.postcode.value.trim(),country:form.elements.country.value}}
let areaCheckTimer;
async function refreshCircumEligibility(){const address=checkoutAddress(),circum=document.querySelector('input[value="circum"]'),standard=document.querySelector('input[value="standard"]'),message=document.querySelector('#service-area-message');message.className='service-area-message';if(!address.address||!address.city||!address.postcode){circum.disabled=true;message.textContent='Enter your address, city and postcode to check Circum Same Day availability.';if(circum.checked)standard.checked=true;renderCheckoutTotals();return}message.textContent='Checking Circum Same Day availability…';try{const result=await window.HaloDelivery.checkServiceArea(address);circum.disabled=!result.eligible;if(result.eligible){message.classList.add('available');message.textContent='✓ Circum Same Day is available for this address.'}else{message.classList.add('unavailable');message.textContent='⚡ Circum Same Day is currently available only within London and surrounding service areas.';if(circum.checked)standard.checked=true}}catch(e){circum.disabled=true;message.classList.add('unavailable');message.textContent='Circum availability could not be confirmed. Standard Delivery remains available.';if(circum.checked)standard.checked=true}renderCheckoutTotals()}
document.querySelectorAll('input[name="deliveryMethod"]').forEach(input=>input.addEventListener('change',renderCheckoutTotals));
['address','city','postcode'].forEach(name=>document.querySelector(`#checkout-form [name="${name}"]`).addEventListener('input',()=>{clearTimeout(areaCheckTimer);areaCheckTimer=setTimeout(refreshCircumEligibility,250)}));
document.querySelector('#checkout-form [name="country"]').addEventListener('change',refreshCircumEligibility);
document.querySelector('#checkout-button').onclick=()=>{checkoutSubtotal=cart.reduce((s,x)=>s+x.price*x.quantity,0);checkoutDiscount=appliedDiscount==='HALO10'?checkoutSubtotal*.1:0;document.querySelector('input[value="standard"]').checked=true;document.querySelector('#checkout-items').innerHTML=cart.map(x=>`<div class="checkout-summary-item"><img src="${x.image}" alt=""><span>${x.title}<br><small>${x.subtitle} × ${x.quantity}</small></span><b>${money(x.price*x.quantity)}</b></div>`).join('');renderCheckoutTotals();closeAll();document.querySelector('#checkout-modal').showModal()};
document.querySelector('#checkout-form').onsubmit=e=>{e.preventDefault();const method=selectedDeliveryMethod();toast(`${window.HaloDelivery.METHODS[method].label} selected — continue with secure payment`)};
document.querySelector('[data-checkout-close]').onclick=()=>document.querySelector('#checkout-modal').close();
renderCart();loadProducts();
